global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "school-services"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8888
          - host.docker.internal:8091
          - host.docker.internal:8085
          - host.docker.internal:8086
          - host.docker.internal:8087
          - host.docker.internal:8088
          - host.docker.internal:8089
          - host.docker.internal:8090
          - host.docker.internal:8761
          - host.docker.internal:9999
